Tillascope.WebUI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Tillascope.Domain.Entities;

namespace Tillascope.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

Tillascope.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;

namespace Tillascope.WebUI.Models
{
    // This 'view model' is not part of the domain model. 
    
    // Its just a convenient place for passing data between the controller and the view.
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }

        public int TotalPages
        {
        get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

Tillascope.WebUI/Models/ProductsListViewModel.cs
using System.Collections.Generic;
using Tillascope.Domain.Entities;

namespace Tillascope.WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

Tillascope.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting.Metadata.W3cXsd2001;
using System.Web;
using System.Web.Mvc;
using Tillascope.Domain.Abstract;
using Tillascope.Domain.Entities;
using Tillascope.WebUI.Models;

namespace Tillascope.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;

        // GET: Cart
        public CartController(IProductRepository repo, IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                // Cart = GetCart(),
                ReturnUrl = returnUrl,
                Cart = cart
            });
        }
        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }

        /* private Cart GetCart() {
             Cart cart = (Cart)Session["Cart"];
             if (cart == null)
             {
                 cart = new Cart();
                 Session["Cart"] = cart;
             }
             return cart;
         }*/
    }
}

Tillascope.WebUI/Controllers/CategoryListController.cs
using System;
using System.Collections.Generic;
using System.EnterpriseServices;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tillascope.Domain.Abstract;

namespace Tillascope.WebUI.Controllers
{
    public class CategoryListController : Controller
    {
        private IProductRepository repository;

        public CategoryListController(IProductRepository repo)
        {
            repository = repo;
        }
        // GET: CategoryList
        public PartialViewResult Menu(string category = null)
        {
            // Send the selected category to the view with viewbag.
            ViewBag.SelectedCategory = category;

            /*return ("Hello from the categoryList Controller");*/
            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(categories);
        }
    }
}

Tillascope.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tillascope.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        public ActionResult Care()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Tillascope.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tillascope.Domain.Abstract;
using Tillascope.Domain.Entities;
using Tillascope.WebUI.Models;

namespace Tillascope.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int PageSize = 4;

        public ProductController(IProductRepository productRepository)
        {
            this.repository = productRepository;
        }
        public ViewResult List(string category, int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = repository.Products
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductId)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? repository.Products.Count() : repository.Products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }
    }
}

Tillascope.WebUI/Views/Cart/Checkout.cshtml
@model Tillascope.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "Tillascope: Checkout";
    ViewBag.Cart = "Your cart";
}
<div class="col-md-8 col-md-offset-2">
    <h2>Check out now</h2>
    <p>Please enter your detail, and we'll ship your goods right away!</p>

    @using (Html.BeginForm())
    {

        <div class="form-horizontal">
            <hr />
            <h3>Ship to</h3>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <hr />
            <h3>Address</h3>

            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
                {
                    <div class="form-group">
                        <label class="control-label col-md-2">@(property.DisplayName ?? property.PropertyName)</label>
                        <div class="col-md-10">
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                        </div>
                    </div>
                       
                }
            }
           
            <hr />
            <h3>Options</h3>

            <div class="form-group">
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.GiftWrap)
                        Gift wrap these items
                        @Html.ValidationMessageFor(model => model.GiftWrap, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Complete Order" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to Cart", "Index")
    </div>
</div>

Tillascope.WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Tillascope: Order Completed";
}

<h2>Thanks</h2>
<p>Thanks for placing your order. We'll ship your goods as soon as possible!</p>

Tillascope.WebUI/Views/Cart/Index.cshtml
@model Tillascope.WebUI.Models.CartIndexViewModel
@{
    ViewBag.Title = "Your cart";
    ViewBag.Cart = "Your cart";
}


<div class="col-md-9" >
    <section>
        <div class="main-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="jumbotron">
                        <span class="h3">
                            @ViewBag.Title
                        </span>
                    </div>
                </div>
                @foreach (var line in Model.Cart.Lines)
                {
                <div class="row panel" style="padding:10px;">
                    <div class="col-md-3">
                        <img src="~/Content/Images/maria6.jpg" style="width:100%;" />
                    </div>
                    <div class="col-md-6">
                        <span class="h3">@line.Product.Name</span>
                        <br />
                        <span class="small">Category: <b>@line.Product.Category</b></span>
                        <br />
                        <span class="h6">Price: <b>@line.Product.Price.ToString("c")</b></span>
                        <br />
                        @using (Html.BeginForm("RemoveFromCart", "Cart"))
                        {
                            @Html.Hidden("ProductId", line.Product.ProductId)
                            @Html.HiddenFor(x => x.ReturnUrl)
                            <input class="btn btn-sm btn-warning" type="submit" value="Remove" />
                        }
                    </div>
                    <div class="col-md-3 ta-c" style="padding-right:0;">
                        <div class="row bubbleRow">
                            <div class="bubble">
                              
                                <span class="glyphicon glyphicon-arrow-up"></span>
                            </div>
                        </div>
                        <div class="row bubbleRow" style="text-align:right;">
                            <span class="h3">@line.Quantity</span>
                        </div>
                        <div class="row bubbleRow">
                            <div class="bubble">
                                <span class="glyphicon glyphicon-arrow-down"></span>
                            </div>
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </section>
</div>
<div class="col-md-3">
    <aside>
        <div class="continueShopping"><a class="btn btn-primary continueShoppingBtn" href="@Model.ReturnUrl">Continue shopping</a></div>
        <div class="sidebar">

            <div class="container-fluid">
                <img src="~/Content/Images/logowhite.jpg" style="width:50px" />
                <span class="h4" style="margin-top:10px;">TILLASCOPE</span>
            </div>

            <hr />
            <span class="h4">Summary</span>
            <br />
            <br />
            <div class="container cart-summary" style="width:100%;">
                <div class="row">
                    <div class="col-md-9 ta-l">
                        <span>Subtotal</span>
                    </div>
                    <div class="col-md-3 ta-r">
                        @Model.Cart.ComputeTotalValue().ToString("c")
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-9 ta-l">
                        <span>Estimated Delivery and Handling</span>
                    </div>
                    <div class="col-md-3 ta-r">
                        <span>£0.00 </span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-9 ta-l">
                        <span><b>Total</b></span>
                    </div>
                    <div class="col-md-3 ta-r">
                        <b>
                            @Model.Cart.ComputeTotalValue().ToString("c")
                        </b>
                    </div>
                </div>
                <br />

            </div>
        </div>
    </aside>
    <br />
    <div class="continueShopping">
    @Html.ActionLink("Go to Checkout", "Checkout", null, new {  @class = "btn btn-primary continueShoppingBtn"})
    </div>
</div>

Tillascope.WebUI/Views/Cart/Summary.cshtml
@model Tillascope.Domain.Entities.Cart
    <div class="navbar-right" style="margin:0 20px;">
        @Html.ActionLink("Checkout", "Index", "Cart",
       new {  returnUrl = Request.Url.PathAndQuery },
       new {  @class = "btn btn-default navbar-btn" })
    </div>

<div class="navbar-text navbar-right">
    <b>Your cart:</b>
    @Model.Lines.Sum(x => x.Quantity) item(s),
    @Model.ComputeTotalValue().ToString("c")
</div>

Tillascope.WebUI/Views/CategoryList/Menu.cshtml
@model IEnumerable<string>


<div style="padding-bottom:5px;">
    <span class="h5">Categories</span>
</div>
    @Html.ActionLink("All Products", "List", "Product", null, new { @class = "btn btn-block btn-default btn-md" })

    @foreach (var link in Model)
    {
        @Html.RouteLink(link, new
        {
            controller = "Product",
            action = "List",
            category = link,
            page = 1
        }, new
        {
            @class = "btn btn-block btn-default btn-md" + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
        });
    }

Tillascope.WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "Our Story";
}
<div class="row">
        <img src="~/Content/Images/TILLASCOPE (1).png" style="width:100%;" />
</div>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Tillascope.WebUI/Views/Home/Care.cshtml
@{
    ViewBag.Title = "Tillandsia Care";
}
<div class="row">
    <img src="~/Content/Images/TILLASCOPE (2).png" style="width:100%;" />
</div>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Tillascope.WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<div class="row">
    <div class="jumbotron">
        <span class="h3">
            @ViewBag.Title
        </span>
    </div>
</div>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Tillascope.WebUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="row">
    <img src="~/Content/Images/TILLASCOPE.png" style="width:100%;" />
</div>


<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Tillascope.WebUI/Views/Product/List.cshtml
@using Tillascope.WebUI.HtmlHelpers
@model Tillascope.WebUI.Models.ProductsListViewModel

@{
    ViewBag.Title = "Products";
}
<div class="row">
    <img src="~/Content/Images/TILLASCOPE (3).png" style="width:100%;" />
</div>
<br />
@{var count = 0;
    foreach (var p in Model.Products)
    {
        if (count%4 == 0)
        {
            <div class="row"></div>
        }

        count++;
    <div class="col-md-3">
        
            @Html.Partial("ProductSummary", p)
            
    </div>

    } 
}
<div class="row"></div>
<div class="row">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
</div>

Tillascope.WebUI/Views/Shared/ProductSummary.cshtml
@model Tillascope.Domain.Entities.Product



<div class="panel">
    <div class="panel panel-header">
        <span class="h4">@Model.Name</span>
    </div>
    <div class="panel panel-body">
        <img class="listImage" src="~/Content/Images/maria6.jpg" />

        <span class="pull-left w-50 label label-primary fs-10">@Model.Price.ToString("c")</span>
        
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
                @Html.HiddenFor(x => x.ProductId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit"  class="pull-right w-50 label label-default" style="display:inline;" value="Add to cart" />
           
        }
       @* <a class="pull-right w-50 label label-default">Add to cart</a>*@
    </div>
    <div class="panel panel-footer">
        <span class="p">@Model.Description.Substring(0, 75)...</span> <a href="#">Read more</a>
    </div>
    @*<a class="btn btn-default">Buy it now...</a>*@
</div>

Tillascope.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">TILLASCOPE</a>
                </div>
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Our Story", "About", "Home")</li>
                    <li>@Html.ActionLink("Tillandsia Care", "Care", "Home")</li>
                    <li>@Html.ActionLink("Products", "List", "Product")</li>
                </ul>
                @Html.Action("Summary", "Cart");
            </div>
        </nav>
        @if (ViewBag.Cart == "Your cart")
        {
            @RenderBody()
        }
        else
        {
            <div class="col-md-3">
                <aside>
                    <div class="sidebar">

                        <div class="container-fluid">
                            <img src="~/Content/Images/logowhite.jpg" style="width:100%" />
                        </div>
                        @Html.Action("Menu", "CategoryList")
                        
                    </div>
                </aside>
            </div>
            <div class="col-md-9">
                <section>
                    <div class="main-body">
                        <div class="container-fluid">
                            @RenderBody()
                        </div>
                    </div>
                </section>
            </div>
        }
    </div>
    
      
</body>
</html>